spring:
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?useSSL=false&serverTimezone=UTC
    username: root
    password: localmysql1234

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace