# Use root as user credentials
version: '3.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: localmysql1234
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

networks:
  default:
    external:
      name: mysql
